### ISSUE TITLE
bsnb.plot() not working in spyder

### ISSUE THREAD

**Issue by harshal5789** [biosignalsplux/biosignalsnotebooks#1]
when i use command, 
bsnb.plot([time], [data_list_Ch4], x_axis_label="Time (s)", y_axis_label="Raw Data-EEG")
it shows no graph in spyder console. 

plt.show() also not working in spyder.

![78135292-46ee3780-743f-11ea-87e2-7084d83ac591](https://user-images.githubusercontent.com/62555471/78135573-b9f7ae00-743f-11ea-907c-e36c7d4cf585.png)

**Comment by ruivarandas** [comment]
biosignalsnotebooks package uses Bokeh to render plots. Once Spyder does [not support this type of plots](https://github.com/spyder-ide/spyder/issues/9423), the alternative is to save the plot to a local file and then open it in a web browser.

This functionality was added in the 0.5.16 version using the line of code:
`bsnb.plot(<time>, <data>, save_plot=True, file_name="test_plot")`
