### ISSUE TITLE
Error loading biosignalsplux/biosignalsnotebooks/mybinder_complete!

### ISSUE THREAD

**Issue by chepo92** [biosignalsplux/biosignalsnotebooks#3]
Log output:

Your session is taking longer than usual to start!
![Screenshot_2021-06-02 GitHub biosignalsplux biosignalsnotebooks mybinder_complete](https://user-images.githubusercontent.com/26207806/120506874-509d6300-c394-11eb-9da7-9ed3b01c6c27.png)

**Comment by GRamosPlux** [comment]
Dear @chepo92,

In the name of the entire **PLUX** team I would like to thank you for opening this issue!
Your perception is totally right, unfortunately the size of our repository  exceeded the memory limit provided by [mybinder.org](https://mybinder.org/).
Our team will try to find a solution to this obstacle, in the meantime, the following workaround can provide a path to edit the Notebooks:

1. Install the **Jupyter Notebook** into your local working environment: [Download, Install and Execute Jupyter Notebook Environment](https://biosignalsplux.com/learn/notebooks/Categories/Install/prepare_jupyter_rev.php);
2. Download the editable version of the Notebook by pressing the top-left corner icon: https://user-images.githubusercontent.com/49654007/120632667-1d74d580-c461-11eb-8d0f-5a57251bc081.mp4
3. Open it in your local environment: https://user-images.githubusercontent.com/49654007/120633430-08e50d00-c462-11eb-87ba-05b241587a98.mp4

Despite not ideal, I truly hope that this workaround can help you minimize the negative impact of the issue that you gently reported.
We will keep this issue open until a definitive solution is publicly available.

**My best and sincere regards,**
@GRamosPlux
