### ISSUE TITLE
Problem importing biosignalsnotebooks 

### ISSUE THREAD

**Issue by chepo92** [biosignalsplux/biosignalsnotebooks#4]
I'm having trouble importing,
I'm using anaconda navigator for environment management, 
I have installed using `pip install biosignalsnotebooks`
in my local jupyter notebook, runing `import biosignalsnotebooks as bsnb` takes forever
I have tryed in python 3.6 and 3.8 and in command line, some times it never ends and some times it quits python
```
Python 3.6.13 (default, Feb 19 2021, 05:17:09) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import biosignalsnotebooks as bsnb
(Python 36) C:\Users\Axel>
```
```
(MachineLearning) C:\Users\Axel>python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import biosignalsnotebooks as bsnb
```

launching python (3.6 and 3.8) in verbose mode throws the following logs, i'm attaching just the last lines as the log is huge when importing, in both cases it hangs after 
`# code object from 'C:\\Users\\Axel\\.conda\\envs\\{environment}\\lib\\site-packages\\magic\\__pycache__\\compat.cpython-{py version}.pyc'`

 
[log36.txt](https://github.com/biosignalsplux/biosignalsnotebooks/files/6601146/log36.txt)
[log38.txt](https://github.com/biosignalsplux/biosignalsnotebooks/files/6601147/log38.txt)

**Comment by GRamosPlux** [comment]
Dear @chepo92,

Thank you very much for creating this new issue, it will certainly be useful to other members of our community!
I need to apologize for the late reply, hoping that this message still reaches you in an appropriate moment.

Taking into consideration the information that you gently provided, our team tried to replicate the reported event.
Despite not being able to reproduce the endless import call, some issues were detected in the past with the **python-magic** package (used by **biosignalsnotebooks** package).

Typically, the procedure reported on the following reply is effective in solving a great set of the problems that we faced in the past with **python-magic**:

- [Uninstall/Re-Install python-magic](https://github.com/Yelp/elastalert/issues/1927#issuecomment-425040424)

Despite not being totally sure if this standard procedure will be effective in solving the reported issue, it can be a good first approach to explore the problem.

I will carefully wait for your kind feedback regarding the effectiveness of the previous procedure!

**My best and sincere regards,**
@GRamosPlux
